AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ExampleJavaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.ordina.workshop.sparkinglambda.LambdaHandler
      CodeUri: ../../../build/libs/SparkingLambda-1.0-all.jar
      Timeout: 30
      Runtime: java8
      Events:
        Sum:
          Type: Api
          Properties:
            Path: /calc/sum
            Method: post
        Multiplication:
          Type: Api
          Properties:
            Path: /calc/multi
            Method: post
        Subtraction:
          Type: Api
          Properties:
            Path: /calc/sub
            Method: post
        Division:
          Type: Api
          Properties:
            Path: /calc/div
            Method: post